### ISSUE TITLE
bug: Subgraph docker-compose error

### ISSUE THREAD

**Issue by dentropy** [scaffold-eth/scaffold-eth-2#387]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

On branch https://github.com/scaffold-eth/scaffold-eth-2/tree/subgraph-package
``` logs
Creating network "graph-node_default" with the default driver
Creating graph-node_ipfs_1     ... done
Creating graph-node_postgres_1 ... done
Creating graph-node_graph-node_1 ... done
Attaching to graph-node_postgres_1, graph-node_ipfs_1, graph-node_graph-node_1
ipfs_1        | Changing user to ipfs
ipfs_1        | ipfs version 0.10.0
postgres_1    | The files belonging to this database system will be owned by user "postgres".
postgres_1    | This user must also own the server process.
postgres_1    | 
ipfs_1        | generating ED25519 keypair...done
ipfs_1        | peer identity: 12D3KooWAn33s6eySmuUwdAphVGUSLR2o8jQrRh1mgxqXqGY9WEW
ipfs_1        | initializing IPFS node at /data/ipfs
ipfs_1        | to get started, enter:
ipfs_1        | 
ipfs_1        | 	ipfs cat /ipfs/QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc/readme
ipfs_1        | 
postgres_1    | The database cluster will be initialized with locale "en_US.utf8".
postgres_1    | The default database encoding has accordingly been set to "UTF8".
postgres_1    | The default text search configuration will be set to "english".
postgres_1    | 
postgres_1    | Data page checksums are disabled.
postgres_1    | 
postgres_1    | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1    | creating subdirectories ... ok
postgres_1    | selecting dynamic shared memory implementation ... posix
postgres_1    | selecting default max_connections ... 100
postgres_1    | selecting default shared_buffers ... 128MB
postgres_1    | selecting default time zone ... Etc/UTC
postgres_1    | creating configuration files ... ok
postgres_1    | running bootstrap script ... ok
graph-node_1  | Waiting for IPFS (ipfs:5001)
ipfs_1        | Initializing daemon...
ipfs_1        | go-ipfs version: 0.10.0-64b532f
ipfs_1        | Repo version: 11
ipfs_1        | System version: amd64/linux
ipfs_1        | Golang version: go1.16.7
ipfs_1        | 2023/06/24 16:52:40 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
postgres_1    | performing post-bootstrap initialization ... ok
postgres_1    | syncing data to disk ... ok
postgres_1    | 
postgres_1    | initdb: warning: enabling "trust" authentication for local connections
postgres_1    | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1    | --auth-local and --auth-host, the next time you run initdb.
postgres_1    | 
postgres_1    | Success. You can now start the database server using:
postgres_1    | 
postgres_1    |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1    | 
postgres_1    | waiting for server to start....2023-06-24 16:52:41.125 UTC [48] LOG:  starting PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgres_1    | 2023-06-24 16:52:41.127 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1    | 2023-06-24 16:52:41.140 UTC [49] LOG:  database system was shut down at 2023-06-24 16:52:40 UTC
postgres_1    | 2023-06-24 16:52:41.144 UTC [48] LOG:  database system is ready to accept connections
postgres_1    |  done
postgres_1    | server started
postgres_1    | CREATE DATABASE
postgres_1    | 
postgres_1    | 
postgres_1    | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1    | 
postgres_1    | waiting for server to shut down....2023-06-24 16:52:41.574 UTC [48] LOG:  received fast shutdown request
postgres_1    | 2023-06-24 16:52:41.575 UTC [48] LOG:  aborting any active transactions
postgres_1    | 2023-06-24 16:52:41.577 UTC [48] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
postgres_1    | 2023-06-24 16:52:41.577 UTC [50] LOG:  shutting down
postgres_1    | 2023-06-24 16:52:41.593 UTC [48] LOG:  database system is shut down
postgres_1    |  done
postgres_1    | server stopped
postgres_1    | 
postgres_1    | PostgreSQL init process complete; ready for start up.
postgres_1    | 
postgres_1    | 2023-06-24 16:52:41.696 UTC [1] LOG:  starting PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgres_1    | 2023-06-24 16:52:41.696 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1    | 2023-06-24 16:52:41.696 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1    | 2023-06-24 16:52:41.698 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1    | 2023-06-24 16:52:41.702 UTC [62] LOG:  database system was shut down at 2023-06-24 16:52:41 UTC
postgres_1    | 2023-06-24 16:52:41.707 UTC [1] LOG:  database system is ready to accept connections
ipfs_1        | Swarm listening on /ip4/127.0.0.1/tcp/4001
ipfs_1        | Swarm listening on /ip4/127.0.0.1/udp/4001/quic
ipfs_1        | Swarm listening on /ip4/192.168.32.3/tcp/4001
ipfs_1        | Swarm listening on /ip4/192.168.32.3/udp/4001/quic
ipfs_1        | Swarm listening on /p2p-circuit
ipfs_1        | Swarm announcing /ip4/127.0.0.1/tcp/4001
ipfs_1        | Swarm announcing /ip4/127.0.0.1/udp/4001/quic
ipfs_1        | Swarm announcing /ip4/192.168.32.3/tcp/4001
ipfs_1        | Swarm announcing /ip4/192.168.32.3/udp/4001/quic
ipfs_1        | Swarm announcing /ip4/216.249.57.2/udp/65435/quic
ipfs_1        | API server listening on /ip4/0.0.0.0/tcp/5001
ipfs_1        | WebUI: http://0.0.0.0:5001/webui
ipfs_1        | Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
ipfs_1        | Daemon is ready
graph-node_1  | Waiting for Postgres (postgres:5432)
graph-node_1  | Jun 24 16:52:47.384 INFO Graph Node version: 0.31.0 (2023-06-12)
graph-node_1  | Jun 24 16:52:47.385 WARN GRAPH_POI_ACCESS_TOKEN not set; might leak POIs to the public via GraphQL
graph-node_1  | Jun 24 16:52:47.385 INFO Generating configuration from command line arguments
graph-node_1  | Jun 24 16:52:47.386 WARN No fork base URL specified, subgraph forking is disabled
graph-node_1  | Jun 24 16:52:47.386 INFO Starting up
graph-node_1  | Jun 24 16:52:47.387 INFO Trying IPFS node at: http://ipfs:5001/
graph-node_1  | Jun 24 16:52:47.408 INFO Successfully connected to IPFS node at: http://ipfs:5001/
graph-node_1  | Jun 24 16:52:47.410 INFO Creating transport, capabilities: archive, traces, url: http://host.docker.internal:8545, provider: localhost-rpc-0
graph-node_1  | Jun 24 16:52:47.417 WARN Expensive queries file not set to a valid file: /etc/graph-node/expensive-queries.txt
graph-node_1  | Jun 24 16:52:47.437 INFO Connecting to Postgres, weight: 1, conn_pool_size: 10, url: postgresql://graph-node:HIDDEN_PASSWORD@postgres:5432/graph-node?sslmode=prefer, pool: main, shard: primary
graph-node_1  | Jun 24 16:52:47.438 INFO Pool successfully connected to Postgres, pool: main, shard: primary, component: Store
graph-node_1  | Jun 24 16:52:47.447 INFO Setting up fdw, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | Jun 24 16:52:47.460 INFO Running migrations, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | Jun 24 16:52:48.296 INFO Migrations finished, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | Jun 24 16:52:48.297 INFO Mapping primary, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | thread 'tokio-runtime-worker' panicked at 'Database does not use C locale. Please check the graph-node documentation for how to set up the database locale: database collation is `en_US.utf8` but must be `C`', store/postgres/src/connection_pool.rs:988:13
graph-node_1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
graph-node_1  | Jun 24 16:52:48.303 CRIT Database does not use C locale. Please check the graph-node documentation for how to set up the database locale, error: database collation is `en_US.utf8` but must be `C`, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(18), ...)', /graph-node/store/postgres/src/connection_pool.rs:497:10
graph-node_graph-node_1 exited with code 101

```

### Expected Behavior

``` logs
Creating network "graph-node_default" with the default driver
Creating graph-node_ipfs_1     ... done
Creating graph-node_postgres_1 ... done
Creating graph-node_graph-node_1 ... done
Attaching to graph-node_ipfs_1, graph-node_postgres_1, graph-node_graph-node_1
postgres_1    | The files belonging to this database system will be owned by user "postgres".
postgres_1    | This user must also own the server process.
postgres_1    | 
postgres_1    | The database cluster will be initialized with locale "C".
postgres_1    | The default text search configuration will be set to "english".
postgres_1    | 
postgres_1    | Data page checksums are disabled.
ipfs_1        | Changing user to ipfs
postgres_1    | 
postgres_1    | fixing permissions on existing directory /var/lib/postgresql/data ... ok
ipfs_1        | ipfs version 0.10.0
graph-node_1  | Waiting for IPFS (ipfs:5001)
ipfs_1        | generating ED25519 keypair...done
ipfs_1        | peer identity: 12D3KooWS6fcwEmGeNB2RB6Bhx6etw4yB7YvFxnh1ctRgziwaxVj
ipfs_1        | initializing IPFS node at /data/ipfs
postgres_1    | creating subdirectories ... ok
ipfs_1        | to get started, enter:
ipfs_1        | 
ipfs_1        | 	ipfs cat /ipfs/QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc/readme
ipfs_1        | 
postgres_1    | selecting dynamic shared memory implementation ... posix
postgres_1    | selecting default max_connections ... 100
postgres_1    | selecting default shared_buffers ... 128MB
postgres_1    | selecting default time zone ... Etc/UTC
postgres_1    | creating configuration files ... ok
postgres_1    | running bootstrap script ... ok
ipfs_1        | Initializing daemon...
ipfs_1        | go-ipfs version: 0.10.0-64b532f
ipfs_1        | Repo version: 11
ipfs_1        | System version: amd64/linux
ipfs_1        | Golang version: go1.16.7
ipfs_1        | 2023/06/24 16:49:03 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
postgres_1    | performing post-bootstrap initialization ... ok
postgres_1    | syncing data to disk ... ok
postgres_1    | 
postgres_1    | initdb: warning: enabling "trust" authentication for local connections
postgres_1    | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1    | --auth-local and --auth-host, the next time you run initdb.
postgres_1    | 
postgres_1    | Success. You can now start the database server using:
postgres_1    | 
postgres_1    |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1    | 
postgres_1    | waiting for server to start....2023-06-24 16:49:03.808 UTC [48] LOG:  starting PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgres_1    | 2023-06-24 16:49:03.810 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1    | 2023-06-24 16:49:03.815 UTC [49] LOG:  database system was shut down at 2023-06-24 16:49:03 UTC
postgres_1    | 2023-06-24 16:49:03.820 UTC [48] LOG:  database system is ready to accept connections
postgres_1    |  done
postgres_1    | server started
postgres_1    | CREATE DATABASE
postgres_1    | 
postgres_1    | 
postgres_1    | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1    | 
postgres_1    | 2023-06-24 16:49:04.459 UTC [48] LOG:  received fast shutdown request
postgres_1    | waiting for server to shut down....2023-06-24 16:49:04.460 UTC [48] LOG:  aborting any active transactions
postgres_1    | 2023-06-24 16:49:04.461 UTC [48] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
postgres_1    | 2023-06-24 16:49:04.461 UTC [50] LOG:  shutting down
postgres_1    | 2023-06-24 16:49:04.499 UTC [48] LOG:  database system is shut down
postgres_1    |  done
postgres_1    | server stopped
postgres_1    | 
postgres_1    | PostgreSQL init process complete; ready for start up.
postgres_1    | 
postgres_1    | 2023-06-24 16:49:04.579 UTC [1] LOG:  starting PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgres_1    | 2023-06-24 16:49:04.579 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1    | 2023-06-24 16:49:04.579 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1    | 2023-06-24 16:49:04.594 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1    | 2023-06-24 16:49:04.598 UTC [62] LOG:  database system was shut down at 2023-06-24 16:49:04 UTC
postgres_1    | 2023-06-24 16:49:04.604 UTC [1] LOG:  database system is ready to accept connections
ipfs_1        | Swarm listening on /ip4/127.0.0.1/tcp/4001
ipfs_1        | Swarm listening on /ip4/127.0.0.1/udp/4001/quic
ipfs_1        | Swarm listening on /ip4/192.168.16.2/tcp/4001
ipfs_1        | Swarm listening on /ip4/192.168.16.2/udp/4001/quic
ipfs_1        | Swarm listening on /p2p-circuit
ipfs_1        | Swarm announcing /ip4/127.0.0.1/tcp/4001
ipfs_1        | Swarm announcing /ip4/127.0.0.1/udp/4001/quic
ipfs_1        | Swarm announcing /ip4/192.168.16.2/tcp/4001
ipfs_1        | Swarm announcing /ip4/192.168.16.2/udp/4001/quic
ipfs_1        | Swarm announcing /ip4/216.249.57.2/udp/33103/quic
ipfs_1        | API server listening on /ip4/0.0.0.0/tcp/5001
ipfs_1        | WebUI: http://0.0.0.0:5001/webui
ipfs_1        | Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
ipfs_1        | Daemon is ready
graph-node_1  | Waiting for Postgres (postgres:5432)
graph-node_1  | Jun 24 16:49:11.051 INFO Graph Node version: 0.31.0 (2023-06-12)
graph-node_1  | Jun 24 16:49:11.052 WARN GRAPH_POI_ACCESS_TOKEN not set; might leak POIs to the public via GraphQL
graph-node_1  | Jun 24 16:49:11.052 INFO Generating configuration from command line arguments
graph-node_1  | Jun 24 16:49:11.052 WARN No fork base URL specified, subgraph forking is disabled
graph-node_1  | Jun 24 16:49:11.052 INFO Starting up
graph-node_1  | Jun 24 16:49:11.052 INFO Trying IPFS node at: http://ipfs:5001/
graph-node_1  | Jun 24 16:49:11.063 INFO Successfully connected to IPFS node at: http://ipfs:5001/
graph-node_1  | Jun 24 16:49:11.066 INFO Creating transport, capabilities: archive, traces, url: http://host.docker.internal:8545, provider: localhost-rpc-0
graph-node_1  | Jun 24 16:49:11.079 WARN Expensive queries file not set to a valid file: /etc/graph-node/expensive-queries.txt
graph-node_1  | Jun 24 16:49:11.105 INFO Connecting to Postgres, weight: 1, conn_pool_size: 10, url: postgresql://graph-node:HIDDEN_PASSWORD@postgres:5432/graph-node?sslmode=prefer, pool: main, shard: primary
graph-node_1  | Jun 24 16:49:11.105 INFO Pool successfully connected to Postgres, pool: main, shard: primary, component: Store
graph-node_1  | Jun 24 16:49:11.119 INFO Setting up fdw, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | Jun 24 16:49:11.135 INFO Running migrations, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | Jun 24 16:49:11.886 INFO Migrations finished, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | Jun 24 16:49:11.888 INFO Mapping primary, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | Jun 24 16:49:11.915 INFO Connecting to Ethereum to get network identifier, capabilities: archive, traces, provider: localhost-rpc-0
graph-node_1  | Jun 24 16:49:12.263 WARN Trying again after net_version RPC call failed (attempt #10) with result Err(failed to send request: error sending request for url (http://host.docker.internal:8545/): error trying to connect: tcp connect error: Connection refused (os error 111)), provider: localhost-rpc-0
graph-node_1  | Jun 24 16:49:12.398 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #10) with result Err(failed to send request: error sending request for url (http://host.docker.internal:8545/): error trying to connect: tcp connect error: Connection refused (os error 111)), provider: localhost-rpc-0
graph-node_1  | Jun 24 16:49:12.563 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #11) with result Err(failed to send request: error sending request for url (http://host.docker.internal:8545/): error trying to connect: tcp connect error: Connection refused (os error 111)), provider: localhost-rpc-0
graph-node_1  | Jun 24 16:49:12.617 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #12) with result Err(failed to send request: error sending request for url (http://host.docker.internal:8545/): error trying to connect: tcp connect error: Connection refused (os error 111)), provider: localhost-rpc-0
graph-node_1  | Jun 24 16:49:13.069 WARN Trying again after net_version RPC call failed (attempt #11) with result Err(failed to send request: error sending request for url (http://host.docker.internal:8545/): error trying to connect: tcp connect error: Connection refused (os error 111)), provider: localhost-rpc-0
graph-node_1  | Jun 24 16:49:13.254 WARN Trying again after net_version RPC call failed (attempt #12) with result Err(failed to send request: error sending request for url (http://host.docker.internal:8545/): error trying to connect: tcp connect error: Connection refused (os error 111)), provider: localhost-rpc-0
```

### Steps To Reproduce

System: Linux PopOS 20.04
Node: 19.0.0

Follow this tutorial,

https://mirror.xyz/cryptomastery.eth/uGHEHnskoVwX-mWjAiidXfGt6QowCoKl_yX4okwZc0E

### Anything else?

I found the solution,

Add and set the POSTGRES_INITDB_ARGS environment variable to the postgres container in docker-compose as below. Just like in the offical graph-node docker-compose file, available [here](https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml). Update [this](https://github.com/scaffold-eth/scaffold-eth-2/blob/subgraph-package/packages/subgraph/graph-node/docker-compose.yml) file.

``` yaml
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
```

**Comment by technophile-04** [comment]
Thanks @dentropy 🙌 

cc @damianmarti could you please check it 🙌

**Comment by damianmarti** [comment]
Thanks @dentropy !!

The fix looks great! 

We are using an old docker-compose.yml file. We should check if we are missing something else.

If you want, you can create a PR to the subgraph-package branch with this fix!

**Comment by dentropy** [comment]
I pulled from the subgraph-package and still have graph-node crashing, here are my logs, gonna submit pull request now

``` logs
➜  graph-node git:(subgraph-package) ✗ docker-compose logs
Attaching to graph-node_graph-node_1, graph-node_ipfs_1, graph-node_postgres_1
graph-node_1  | Waiting for IPFS (ipfs:5001)
graph-node_1  | Waiting for Postgres (postgres:5432)
graph-node_1  | Jul 04 22:15:10.259 INFO Graph Node version: 0.31.0 (2023-06-12)
graph-node_1  | Jul 04 22:15:10.263 WARN GRAPH_POI_ACCESS_TOKEN not set; might leak POIs to the public via GraphQL
graph-node_1  | Jul 04 22:15:10.263 INFO Generating configuration from command line arguments
graph-node_1  | Jul 04 22:15:10.263 WARN No fork base URL specified, subgraph forking is disabled
graph-node_1  | Jul 04 22:15:10.263 INFO Starting up
graph-node_1  | Jul 04 22:15:10.264 INFO Trying IPFS node at: http://ipfs:5001/
graph-node_1  | Jul 04 22:15:10.293 INFO Successfully connected to IPFS node at: http://ipfs:5001/
graph-node_1  | Jul 04 22:15:10.301 INFO Creating transport, capabilities: archive, traces, url: http://host.docker.internal:8545, provider: localhost-rpc-0
graph-node_1  | Jul 04 22:15:10.315 WARN Expensive queries file not set to a valid file: /etc/graph-node/expensive-queries.txt
graph-node_1  | Jul 04 22:15:10.337 INFO Connecting to Postgres, weight: 1, conn_pool_size: 10, url: postgresql://graph-node:HIDDEN_PASSWORD@postgres:5432/graph-node?sslmode=prefer, pool: main, shard: primary
graph-node_1  | Jul 04 22:15:10.338 INFO Pool successfully connected to Postgres, pool: main, shard: primary, component: Store
graph-node_1  | Jul 04 22:15:10.352 INFO Setting up fdw, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | Jul 04 22:15:10.367 INFO Running migrations, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | Jul 04 22:15:11.280 INFO Migrations finished, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | Jul 04 22:15:11.283 INFO Mapping primary, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | thread 'tokio-runtime-worker' panicked at 'Database does not use C locale. Please check the graph-node documentation for how to set up the database locale: database collation is `en_US.utf8` but must be `C`', store/postgres/src/connection_pool.rs:Jul 04 22:15:11.289988: 13
graph-node_1  | CRITnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
graph-node_1  |  Database does not use C locale. Please check the graph-node documentation for how to set up the database locale, error: database collation is `en_US.utf8` but must be `C`, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(18), ...)', /graph-node/store/postgres/src/connection_pool.rs:497:10
postgres_1    | The files belonging to this database system will be owned by user "postgres".
postgres_1    | This user must also own the server process.
postgres_1    | 
postgres_1    | The database cluster will be initialized with locale "en_US.utf8".
postgres_1    | The default database encoding has accordingly been set to "UTF8".
postgres_1    | The default text search configuration will be set to "english".
postgres_1    | 
postgres_1    | Data page checksums are disabled.
postgres_1    | 
postgres_1    | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1    | creating subdirectories ... ok
postgres_1    | selecting dynamic shared memory implementation ... posix
postgres_1    | selecting default max_connections ... 100
postgres_1    | selecting default shared_buffers ... 128MB
postgres_1    | selecting default time zone ... Etc/UTC
postgres_1    | creating configuration files ... ok
postgres_1    | running bootstrap script ... ok
postgres_1    | performing post-bootstrap initialization ... ok
postgres_1    | syncing data to disk ... ok
postgres_1    | 
postgres_1    | 
postgres_1    | Success. You can now start the database server using:
postgres_1    | 
postgres_1    |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1    | 
postgres_1    | initdb: warning: enabling "trust" authentication for local connections
postgres_1    | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1    | --auth-local and --auth-host, the next time you run initdb.
postgres_1    | waiting for server to start....2023-07-04 22:15:03.799 UTC [49] LOG:  starting PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgres_1    | 2023-07-04 22:15:03.801 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1    | 2023-07-04 22:15:03.814 UTC [50] LOG:  database system was shut down at 2023-07-04 22:15:03 UTC
postgres_1    | 2023-07-04 22:15:03.821 UTC [49] LOG:  database system is ready to accept connections
postgres_1    |  done
postgres_1    | server started
postgres_1    | CREATE DATABASE
postgres_1    | 
postgres_1    | 
postgres_1    | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1    | 
postgres_1    | 2023-07-04 22:15:04.092 UTC [49] LOG:  received fast shutdown request
postgres_1    | waiting for server to shut down....2023-07-04 22:15:04.093 UTC [49] LOG:  aborting any active transactions
postgres_1    | 2023-07-04 22:15:04.094 UTC [49] LOG:  background worker "logical replication launcher" (PID 56) exited with exit code 1
postgres_1    | 2023-07-04 22:15:04.094 UTC [51] LOG:  shutting down
postgres_1    | 2023-07-04 22:15:04.109 UTC [49] LOG:  database system is shut down
postgres_1    |  done
postgres_1    | server stopped
postgres_1    | 
postgres_1    | PostgreSQL init process complete; ready for start up.
postgres_1    | 
postgres_1    | 2023-07-04 22:15:04.235 UTC [1] LOG:  starting PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgres_1    | 2023-07-04 22:15:04.235 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1    | 2023-07-04 22:15:04.235 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1    | 2023-07-04 22:15:04.237 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1    | 2023-07-04 22:15:04.241 UTC [63] LOG:  database system was shut down at 2023-07-04 22:15:04 UTC
postgres_1    | 2023-07-04 22:15:04.246 UTC [1] LOG:  database system is ready to accept connections
ipfs_1        | Changing user to ipfs
ipfs_1        | ipfs version 0.10.0
ipfs_1        | generating ED25519 keypair...done
ipfs_1        | peer identity: 12D3KooWSwSDBoCf89PCxgRuwEm2Xd2A7hftuJ4QycDXmkWa6Y6E
ipfs_1        | initializing IPFS node at /data/ipfs
ipfs_1        | to get started, enter:
ipfs_1        | 
ipfs_1        | 	ipfs cat /ipfs/QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc/readme
ipfs_1        | 
ipfs_1        | Initializing daemon...
ipfs_1        | go-ipfs version: 0.10.0-64b532f
ipfs_1        | Repo version: 11
ipfs_1        | System version: amd64/linux
ipfs_1        | Golang version: go1.16.7
ipfs_1        | 2023/07/04 22:15:03 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
ipfs_1        | Swarm listening on /ip4/127.0.0.1/tcp/4001
ipfs_1        | Swarm listening on /ip4/127.0.0.1/udp/4001/quic
ipfs_1        | Swarm listening on /ip4/172.24.0.3/tcp/4001
ipfs_1        | Swarm listening on /ip4/172.24.0.3/udp/4001/quic
ipfs_1        | Swarm listening on /p2p-circuit
ipfs_1        | Swarm announcing /ip4/127.0.0.1/tcp/4001
ipfs_1        | Swarm announcing /ip4/127.0.0.1/udp/4001/quic
ipfs_1        | Swarm announcing /ip4/172.24.0.3/tcp/4001
ipfs_1        | Swarm announcing /ip4/172.24.0.3/udp/4001/quic
ipfs_1        | Swarm announcing /ip4/206.248.184.197/udp/4001/quic
ipfs_1        | API server listening on /ip4/0.0.0.0/tcp/5001
ipfs_1        | WebUI: http://0.0.0.0:5001/webui
ipfs_1        | Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
ipfs_1        | Daemon is ready
➜  graph-node git:(subgraph-package) ✗ docker ps -a
CONTAINER ID   IMAGE                             COMMAND                  CREATED              STATUS                            PORTS                                                                          NAMES
76067678e49e   graphprotocol/graph-node:latest   "start"                  About a minute ago   Exited (101) About a minute ago                                                                                  graph-node_graph-node_1
d9138dd83afd   ipfs/go-ipfs:v0.10.0              "/sbin/tini -- /usr/…"   About a minute ago   Up About a minute                 4001/tcp, 8080-8081/tcp, 4001/udp, 0.0.0.0:5001->5001/tcp, :::5001->5001/tcp   graph-node_ipfs_1
0d701a30921c   postgres                          "docker-entrypoint.s…"   About a minute ago   Up About a minute                 0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                      graph-node_postgres_1
➜  graph-node git:(subgraph-package) ✗ docker logs 76067678e49e
Waiting for IPFS (ipfs:5001)
Waiting for Postgres (postgres:5432)
Jul 04 22:15:10.259 INFO Graph Node version: 0.31.0 (2023-06-12)
Jul 04 22:15:10.263 WARN GRAPH_POI_ACCESS_TOKEN not set; might leak POIs to the public via GraphQL
Jul 04 22:15:10.263 INFO Generating configuration from command line arguments
Jul 04 22:15:10.263 WARN No fork base URL specified, subgraph forking is disabled
Jul 04 22:15:10.263 INFO Starting up
Jul 04 22:15:10.264 INFO Trying IPFS node at: http://ipfs:5001/
Jul 04 22:15:10.293 INFO Successfully connected to IPFS node at: http://ipfs:5001/
Jul 04 22:15:10.301 INFO Creating transport, capabilities: archive, traces, url: http://host.docker.internal:8545, provider: localhost-rpc-0
Jul 04 22:15:10.315 WARN Expensive queries file not set to a valid file: /etc/graph-node/expensive-queries.txt
Jul 04 22:15:10.337 INFO Connecting to Postgres, weight: 1, conn_pool_size: 10, url: postgresql://graph-node:HIDDEN_PASSWORD@postgres:5432/graph-node?sslmode=prefer, pool: main, shard: primary
Jul 04 22:15:10.338 INFO Pool successfully connected to Postgres, pool: main, shard: primary, component: Store
Jul 04 22:15:10.352 INFO Setting up fdw, pool: main, shard: primary, component: ConnectionPool
Jul 04 22:15:10.367 INFO Running migrations, pool: main, shard: primary, component: ConnectionPool
Jul 04 22:15:11.280 INFO Migrations finished, pool: main, shard: primary, component: ConnectionPool
Jul 04 22:15:11.283 INFO Mapping primary, pool: main, shard: primary, component: ConnectionPool
thread 'tokio-runtime-worker' panicked at 'Database does not use C locale. Please check the graph-node documentation for how to set up the database locale: database collation is `en_US.utf8` but must be `C`', store/postgres/src/connection_pool.rs:Jul 04 22:15:11.289988: 13
CRITnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 Database does not use C locale. Please check the graph-node documentation for how to set up the database locale, error: database collation is `en_US.utf8` but must be `C`, pool: main, shard: primary, component: ConnectionPool
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(18), ...)', /graph-node/store/postgres/src/connection_pool.rs:497:10
➜  graph-node git:(subgraph-package) ✗ 
```

**Comment by dentropy** [comment]
Link to my fork with the fix,

https://github.com/dentropy/scaffold-eth-2/blob/subgraph-package/packages/subgraph/graph-node/docker-compose.yml

**Comment by dentropy** [comment]
Pull request submitted, https://github.com/scaffold-eth/scaffold-eth-2/pull/402

**Comment by dentropy** [comment]
Direct link to changed file, [scaffold-eth-2/packages/subgraph/graph-node/docker-compose.yml at subgraph-package · dentropy/scaffold-eth-2 · GitHub](https://github.com/dentropy/scaffold-eth-2/blob/subgraph-package/packages/subgraph/graph-node/docker-compose.yml)
