### ISSUE TITLE
bug: "transaction underpriced" when deploying anything to Base Goerli

### ISSUE THREAD

**Issue by webthethird** [scaffold-eth/scaffold-eth-2#487]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

When I try to deploy any of my contracts to Base Goerli, I get a `ProviderError: transaction underpriced`.

### Expected Behavior

Contracts deploy to Base Goerli.

### Steps To Reproduce

Change `defaultNetwork` to `"baseGoerli"` in hardhat.config.ts or use `yarn deploy --network baseGoerli`

Here is the deploy script which is failing:
https://github.com/FarmshareCSA/Farmshare/blob/dev-zerodev-login/packages/hardhat/deploy/02_deploy_registry_contracts.ts

### Anything else?

```
yarn deploy
(node:42813) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Nothing to compile
No need to generate any newer typings.
deploying "UserRegistry"transaction underpriced {"name":"ProviderError","_stack":"ProviderError: transaction underpriced\n    at HttpProvider.request (/home/webthethird/Ethereum/Farmshare/packages/hardhat/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","code":-32000,"_isProviderError":true} ProviderError: transaction underpriced
    at HttpProvider.request (/home/webthethird/Ethereum/Farmshare/packages/hardhat/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
An unexpected error occurred:

Error: ERROR processing /home/webthethird/Ethereum/Farmshare/packages/hardhat/deploy/02_deploy_registry_contracts.ts:
ProviderError: transaction underpriced
    at HttpProvider.request (/home/webthethird/Ethereum/Farmshare/packages/hardhat/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DeploymentsManager.executeDeployScripts (/home/webthethird/Ethereum/Farmshare/packages/hardhat/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1229:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DeploymentsManager.runDeploy (/home/webthethird/Ethereum/Farmshare/packages/hardhat/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1059:5)
    at async SimpleTaskDefinition.action (/home/webthethird/Ethereum/Farmshare/packages/hardhat/node_modules/hardhat-deploy/src/index.ts:438:5)
    at async Environment._runTaskDefinition (/home/webthethird/Ethereum/Farmshare/packages/hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:333:14)
    at async Environment.run (/home/webthethird/Ethereum/Farmshare/packages/hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:166:14)
    at async SimpleTaskDefinition.action (/home/webthethird/Ethereum/Farmshare/packages/hardhat/node_modules/hardhat-deploy/src/index.ts:584:32)
    at async Environment._runTaskDefinition (/home/webthethird/Ethereum/Farmshare/packages/hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:333:14)
    at async Environment.run (/home/webthethird/Ethereum/Farmshare/packages/hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:166:14)
    at async SimpleTaskDefinition.action (/home/webthethird/Ethereum/Farmshare/packages/hardhat/node_modules/hardhat-deploy/src/index.ts:669:5)
```

**Comment by technophile-04** [comment]
Hey @webthethird, As I can see you guys are using blastApi as RPC provider in [hardhat.configt.ts](https://github.com/FarmshareCSA/Farmshare/blob/38e51857e544c769bbf301ec2f1dbf711d8c80f0/packages/hardhat/hardhat.config.ts#L99C1-L99C1) but you didn't put any `api key` at the end of URL : 

```diff
    baseGoerli: {
-      url: `https://base-goerli.public.blastapi.io`,
+     url: `https://base-goerli.public.blastapi.io/<YOUR_API_KEY>`,   
      accounts: [deployerPrivateKey],
      chainId: 84531,
      gasPrice: 1000000000
    },

```

**Comment by webthethird** [comment]
Actually this issue was resolved by your suggestion in the Telegram chat to add the `gasPrice`! Just forgot to close it here.
