### ISSUE TITLE
Address page in blockexplorer is not working on a Vercel deployment

### ISSUE THREAD

**Issue by Pabl0cks** [scaffold-eth/scaffold-eth-2#730]
Maybe this use case does not make sense, feel free to close the issue if so 🙌

Steps to reproduce:
- Run `yarn install` / `yarn chain` / `yarn deploy` in a fresh SE-2 
- Deploy into Vercel (leaving hardhat as network to have Blockexplorer).
- Open the vercel deployed site and go to Blockexplorer.
- Click in any of the two address from Contract creation (from / to)

<details>
<summary>Here are the vercel logs:</summary>

Error: Directory /var/hardhat/artifacts/build-info not found.
    at O (/var/task/.next/server/app/blockexplorer/address/[address]/page.js:1:7191)
    at z (/var/task/.next/server/app/blockexplorer/address/[address]/page.js:1:7464)
    at em (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131226)
    at /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142926
    at Array.toJSON (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146504)
    at stringify (<anonymous>)
    at eR (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134889)
    at eP (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135332)
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Timeout._onTimeout (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146956)
    
</details>

**Comment by Pabl0cks** [comment]
Ok! Closing this
